name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/10 * * * *'  # Every hour (you can change this)
  workflow_dispatch:     # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the forked repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "alihasnainladhani"
          git config user.email "alihasnain2222@gmail.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/Shahzaib2028/event_registration.git
          git fetch upstream

      - name: Merge upstream/master into forked master
        run: |
          git checkout master
          git merge upstream/master --no-edit

      - name: Push changes to forked master
        run: |
          git push origin master